steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
artifacts:
  objects:
    location: 'gs://my-bluesky-instance/'
    paths: ['dist/*']
